'''
Name:              Create_Gif.py
Description:       Create a Gif with some Pictures & Splice some Pictures
Auther:            KhalilWong
License:           MIT License
Copyright:         Copyright (C) 2019, by KhalilWong
Version:           2.0.0
Date:              2019/07/23
Namespace:         https://github.com/KhalilWong
DownloadURL:       https://github.com/KhalilWong/...
UpdateURL:         https://github.com/KhalilWong/...
'''
################################################################################
import imageio
from PIL import Image
import os
import os.path
import time

################################################################################
def Create_Gif(gif_name,path,fps,PicNames):
    '''
    gif_name： 字符串，所生成的gif文件名，带.gif后缀
    path：     需要合成为gif的图片所在路径
    fps：      帧数
    PicNames:  图片名称集合
    '''
    #
    start = time.time()
    print('Generating...')
    #
    frames = []
    image_list = [os.path.join(path,f) for f in PicNames]
    for image_name in image_list:
        #读取图像文件
        frames.append(imageio.imread(image_name))
    #保存为gif
    imageio.mimwrite(gif_name,frames,'GIF',duration = 1/fps)
    #
    end = time.time()
    print('Generation Done in '+str(round(end-start,10))+' seconds!')
    print(gif_name+' has been generated by '+str(len(PicNames))+' Pictures with fps='+str(fps)+'!')

################################################################################
def Splice_Pics(filename0,filename1,savefilename):
    '''
    filename0：     图0名
    filename1：     图1名
    savefilename：  保存图名
    '''
    #读取两张图
    print('Read Pictures: ' + filename0 + ', ' + filename1)
    image0 = Image.open(filename0)
    image1 = Image.open(filename1)
    #以图0的尺寸做标准，缩放图1
    (w, h) = image0.size
    image1 = image1.resize((w, h), Image.LANCZOS)
    #新建空白的大尺寸（w,2h）图
    spliced_image = Image.new('RGB', (w,2*h))
    #在大图上分别粘贴两张图，box为图片左上角粘贴位置
    spliced_image.paste(image0, box=(0, 0))
    spliced_image.paste(image1, box=(0, h))
    #保存图片
    spliced_image.save(savefilename)
    print(savefilename + ' has been generated!')
    #spliced_image.show()
    spliced_image.close()

################################################################################
def main0():
    #gif文件名
    gif_name='My_Gif.gif'
    #读取文件路径（所在文件夹）
    path=r'E:\M'
    #每秒图片张数
    fps=60
    #图片名集合
    PicNames=['%04d.jpg'%i for i in range(0,365,1)]                             #"%04d"表示在输出i是一个小于4位的整数时,将在前面补0使其总宽度为4位
    #
    Create_Gif(gif_name,path,fps,PicNames)

################################################################################
def main1():
    #读取图片路径（所在文件夹）
    savepath = r'C:\Users\Khali\Desktop'
    path0 = r'C:\Users\Khali\Desktop'
    path1 = r'C:\Users\Khali\Desktop'
    #图片名集合
    SavePicNames = ['cd%04d.png'%i for i in range(0, 1, 1)]                          #"%04d"表示在输出i是一个小于4位的整数时,将在前面补0使其总宽度为4位
    Pic0Names = ['c%04d.png'%i for i in range(0, 1, 1)]                             #"%04d"表示在输出i是一个小于4位的整数时,将在前面补0使其总宽度为4位
    Pic1Names = ['d%04d.png'%i for i in range(0, 1, 1)]                             #"%04d"表示在输出i是一个小于4位的整数时,将在前面补0使其总宽度为4位
    #每秒图片张数
    if(len(SavePicNames) == len(Pic0Names) and len(Pic0Names) == len(Pic1Names)):
        for i in range(len(SavePicNames)):
            SavePic = os.path.join(savepath, SavePicNames[i])
            Pic0 = os.path.join(path0, Pic0Names[i])
            Pic1 = os.path.join(path1, Pic1Names[i])
            Splice_Pics(Pic0, Pic1, SavePic)
    else:
        print('输入图片0，1数不等，或者与保存图片数不等！')

################################################################################
if __name__ == '__main__':
    #
    #main0()
    main1()
